In [1]:
import numpy as np
import pandas as pd

In [2]:

df = pd.Series([1,2,3,4,5])
df1 = pd.Series([1,2,3,4,5])


result = df + df1
print(result)

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [3]:
df1 = pd.Series([1,2,3,4,5])

df2 = pd.Series([1,22,3,41,5])

result = (df1==df2)
print(result)

0     True
1    False
2     True
3    False
4     True
dtype: bool

In [5]:
hf = {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}

result = pd.Series(hf)

print(result)

a    100
b    200
c    300
d    400
e    800
dtype: int64

In [7]:
data = [10, 20, 30, 40, 50]

result = pd.Series(data1)

print(result)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [10]:
data_given = ([100,200,'python',300,400])

result = s2 = pd.to_numeric(pd.Series(data_given), errors='coerce')

print(result)

0    100.0
1    200.0
2      NaN
3    300.0
4    400.0
dtype: float64

In [16]:
hello = [
	['Red', 'Green', 'White'],
	['Red', 'Black'],
	['Yellow']
]

result = pd.Series(hello)

print(result)

0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object

In [17]:
s = pd.Series([1, 2, 'python', 4, 'gandu'])


s_add = pd.concat([s, pd.Series([100, 200])], ignore_index=True)


print(s_add)

0         1
1         2
2    python
3         4
4     gandu
5       100
6       200
dtype: object

In [18]:
s1 = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]})

In [19]:
s1

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83

In [22]:
details = pd.DataFrame({'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
                        'Age': [27, 24, 22, 32],
                        'Address': ['Delhi', 'Kanpur', 'Allahabad', 'Kannauj'],
                        'Qualification': ['Msc', 'MA', 'MCA', 'Phd']})

In [23]:
details

     Name  Age    Address Qualification
0     Jai   27      Delhi           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannauj           Phd